server:
  port: 8025
spring:
  profiles:
    active: dev
  jpa:
    properties:
      javax:
        persistence:
          validation:
            mode: none
      hibernate:
        format_sql: false
    show-sql: true
---
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:h2:mem:PQCs-dev
---
spring:
  config:
    activate:
      on-profile: dev-postgres
  datasource:
    url: jdbc:postgresql://127.0.0.1:5432/PQCs
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: create-drop